[package]
name = "slint_android_camera"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = {version = "1.5.0", features = ["backend-android-activity-05"]}
anyhow = "1"

[lib]
crate-type = ["cdylib"]